version: '3.8'

services:
  FutuBot:
    build: .
    image: futubot:latest
    container_name: FutuBot
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: always
    ports:
      - "11111:11111"
    network_mode: host